# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/ironarachne/chargen
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          cd cmd/chargend
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t ironarachne/chargend:$TAG -t ironarachne/chargend:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ironarachne/chargend:$TAG
          docker push ironarachne/chargend:latest
  deploy:
    machine:
        enabled: true
    steps:
      - run: curl -X POST 'https://portainer.ironarachne.com/api/webhooks/5131af34-6dbc-406c-b997-1a84f68cbcd9'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
